version: '3.8'

services:
  app:
    build: .
    environment:
      - ORIGIN=${ORIGIN}
      - NEWS_API_API_KEY=${NEWS_API_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - MAX_STOCKS=${MAX_STOCKS:-20}
      - MODEL_NAME=${MODEL_NAME}
      - UNIQUE_MONGODB_URI=${UNIQUE_MONGODB_URI}  # Updated URI
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_COLLECTION_NAME=${MONGODB_COLLECTION_NAME}
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"  # Expose MongoDB to host on port 27018
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
